const keywords = [
    // Movies (20 words)
    "Ratatouille (Entertainment)",
    "Titanic (Entertainment)",
    "The Lion King (Entertainment)",
    "Jurassic Park (Entertainment)",
    "Star Wars (Entertainment)",
    "Harry Potter (Entertainment)",
    "Inception (Entertainment)",
    "The Matrix (Entertainment)",
    "Avatar (Entertainment)",
    "Forrest Gump (Entertainment)",
    "Pulp Fiction (Entertainment)",
    "The Godfather (Entertainment)",
    "Shawshank Redemption (Entertainment)",
    "Spirited Away (Entertainment)",
    "Parasite (Entertainment)",
    "Interstellar (Entertainment)",
    "Gladiator (Entertainment)",
    "E.T. (Entertainment)",
    "Toy Story (Entertainment)",
    "Finding Nemo (Entertainment)",
    "The Dark Knight (Entertainment)",
    "Bahubali (Entertainment)",
    "KGF (Entertainment)",
    "Kantara (Entertainment)",
    "RRR (Entertainment)",
    "Pushpa (Entertainment)",
    "Kabali (Entertainment)",

    // Science (20 words)
    "Gravity (Science)",
    "Evolution (Science)",
    "Photosynthesis (Science)",
    "DNA (Science)",
    "Atoms (Science)",
    "Physics (Science)",
    "Chemistry (Science)",
    "Biology (Science)",
    "Astronomy (Science)",
    "Geology (Science)",
    "Experiment (Science)",
    "Hypothesis (Science)",
    "Theory (Science)",
    "Microscope (Science)",
    "Telescope (Science)",
    "Vaccine (Science)",
    "Electricity (Science)",
    "Magnetism (Science)",
    "psychology (Science)",
    "photosynthesis (Science)",

    // Animals (20 words)
    "Tiger (Nature)",
    "Elephant (Nature)",
    "Dolphin (Nature)",
    "Kangaroo (Nature)",
    "Chimpanzee (Nature)",
    "Eagle (Nature)",
    "Shark (Nature)",
    "Penguin (Nature)",
    "Octopus (Nature)",
    "Giraffe (Nature)",
    "Panda (Nature)",
    "Wolf (Nature)",
    "Fox (Nature)",
    "Bear (Nature)",
    "Lion (Nature)",
    "Zebra (Nature)",
    "Crocodile (Nature)",
    "Snake (Nature)",
    "Owl (Nature)",
    "Butterfly (Nature)",
    "Peacock (Nature)",
    "Parrot (Nature)",
    "Pigeon (Nature)",
    "Duck (Nature)",
    "Lizard (Nature)",
    "Crab (Nature)",
    "Dog (Nature)",
    "Cat (Nature)",
    "Horse (Nature)",
    "Sheep (Nature)",
    "Goat (Nature)",
    "Cow (Nature)",
    "Pig (Nature)",

    // Food & Drink (20 words)
    "Banana (Food and Drink)",
    "Pizza (Food and Drink)",
    "Sushi (Food and Drink)",
    "Pasta (Food and Drink)",
    "Taco (Food and Drink)",
    "Burger (Food and Drink)",
    "Chocolate (Food and Drink)",
    "Ice Cream (Food and Drink)",
    "Coffee (Food and Drink)",
    "Tea (Food and Drink)",
    "Smoothie (Food and Drink)",
    "Watermelon (Food and Drink)",
    "Broccoli (Food and Drink)",
    "Bread (Food and Drink)",
    "Cheese (Food and Drink)",
    "Soup (Food and Drink)",
    "Salad (Food and Drink)",
    "Juice (Food and Drink)",
    "Soda (Food and Drink)",
    "Milk (Food and Drink)",
    "Chips (Food and Drink)",
    "Apple (Food and Drink)",
    "Orange (Food and Drink)",
    "Mango (Food and Drink)",
    "Pineapple (Food and Drink)",
    "Strawberry (Food and Drink)",
    "Blueberry (Food and Drink)",

    // Professions (20 words)
    "Doctor (Person)",
    "Astronaut (Person)",
    "Teacher (Person)",
    "Engineer (Person)",
    "Chef (Person)",
    "Artist (Person)",
    "Musician (Person)",
    "Pilot (Person)",
    "Police Officer (Person)",
    "Firefighter (Person)",
    "Lawyer (Person)",
    "Scientist (Person)",
    "Writer (Person)",
    "Farmer (Person)",
    "Architect (Person)",
    "Photographer (Person)",
    "Dancer (Person)",
    "Nurse (Person)",
    "Veterinarian (Person)",
    "Librarian (Person)",

    // Places (General) (20 words)
    "Library (Place)",
    "Hospital (Place)",
    "Museum (Place)",
    "Restaurant (Place)",
    "Supermarket (Place)",
    "Airport (Place)",
    "School (Place)",
    "Park (Place)",
    "Beach (Place)",
    "Forest (Place)",
    "Mountain (Place)",
    "Desert (Place)",
    "Island (Place)",
    "City (Place)",
    "Village (Place)",
    "Bridge (Place)",
    "Castle (Place)",
    "Factory (Place)",
    "Port (Place)",
    "Zoo (Place)",

    //places (specific) (20 words)
    "mount fuji (Place)",
    "mount everest (Place)",
    "pyramids of giza (Place)",
    "great wall of china (Place)",
    "eiffel tower (Place)",
    "statue of liberty (Place)",
    "taj mahal (Place)",
    "burj khalifa (Place)",
    "charminar (Place)",

    // Nature (20 words)
    "Ocean (Nature)",
    "River (Nature)",
    "Lake (Nature)",
    "Volcano (Nature)",
    "Waterfall (Nature)",
    "Rainbow (Nature)",
    "Cloud (Nature)",
    "Sun (Nature)",
    "Moon (Nature)",
    "Star (Nature)",
    "Planet (Nature)",
    "Flower (Nature)",
    "Tree (Nature)",
    "Bush (Nature)",
    "Grass (Nature)",
    "Rock (Nature)",
    "Sand (Nature)",
    "Snow (Nature)",
    "Ice (Nature)",
    "Cave (Nature)",

    // Household Items (20 words)
    "Chair (Thing)",
    "Table (Thing)",
    "Sofa (Thing)",
    "Bed (Thing)",
    "Lamp (Thing)",
    "Mirror (Thing)",
    "Rug (Thing)",
    "Curtain (Thing)",
    "Television (Thing)",
    "Refrigerator (Thing)",
    "Oven (Thing)",
    "Microwave (Thing)",
    "Dishwasher (Thing)",
    "Washing Machine (Thing)",
    "Vacuum Cleaner (Thing)",
    "Broom (Thing)",
    "Mop (Thing)",
    "Clock (Thing)",
    "Vase (Thing)",
    "Plate (Thing)",

    // Clothing & Accessories (20 words)
    "T-shirt (Thing)",
    "Jeans (Thing)",
    "Dress (Thing)",
    "Jacket (Thing)",
    "Shoes (Thing)",
    "Hat (Thing)",
    "Scarf (Thing)",
    "Gloves (Thing)",
    "Socks (Thing)",
    "Boots (Thing)",
    "Sandals (Thing)",
    "Sweater (Thing)",
    "Hoodie (Thing)",
    "Pajamas (Thing)",
    "Belt (Thing)",
    "Wallet (Thing)",
    "Chain (Thing)",
    "Backpack (Thing)",
    "Umbrella (Thing)",
    "Glasses (Thing)",

    // Vehicles (20 words)
    "Rocket (Thing)",
    "Car (Thing)",
    "Bus (Thing)",
    "Train (Thing)",
    "Plane (Thing)",
    "Boat (Thing)",
    "Ship (Thing)",
    "Submarine (Thing)",
    "Helicopter (Thing)",
    "Bicycle (Thing)",
    "Motorcycle (Thing)",
    "Skateboard (Thing)",
    "Scooter (Thing)",
    "Tractor (Thing)",
    "Truck (Thing)",
    "Tricycle (Thing)",
    "Ambulance (Thing)",
    "Fire Truck (Thing)",
    "Hot Air Balloon (Thing)",
    "Spaceship (Thing)",

    // Technology (20 words)
    "Computer (Thing)",
    "Laptop (Thing)",
    "Phone (Thing)",
    "Tablet (Thing)",
    "Camera (Thing)",
    "Microphone (Thing)",
    "Speaker (Thing)",
    "Headphones (Thing)",
    "Keyboard (Thing)",
    "Mouse (Thing)",
    "Printer (Thing)",
    "Scanner (Thing)",
    "Projector (Thing)",
    "Battery (Thing)",
    "Internet (Concept)",
    "Software (Concept)",
    "Robot (Thing)",
    "Drone (Thing)",
    "Smartwatch (Thing)",
    "Virtual Reality Headset (Thing)",

    // Sports (20 words)
    "Football (Activity)",
    "Basketball (Activity)",
    "Soccer (Activity)",
    "Tennis (Activity)",
    "Golf (Activity)",
    "Swimming (Activity)",
    "Running (Activity)",
    "Cycling (Activity)",
    "Volleyball (Activity)",
    "Baseball (Activity)",
    "Hockey (Activity)",
    "Boxing (Activity)",
    "Gymnastics (Activity)",
    "Skiing (Activity)",
    "Snowboarding (Activity)",
    "Surfing (Activity)",
    "Skateboarding (Activity)",
    "Cricket (Activity)",
    "Badminton (Activity)",
    "Rugby (Activity)",

    // Health Conditions (20 words) - Includes Diseases, Disorders, Fractures
    "Down Syndrome (Science)",
    "Flu (Science)",
    "Diabetes (Science)",
    "Heart Attack (Science)",
    "Cancer (Science)",
    "Asthma (Science)",
    "Anxiety (Science)", 
    "Depression (Science)", 
    "Concussion (Science)", 
    "Fracture (Science)", 
    "multiple personality disorder (Science)",
    "Migraine (Science)",
    "testicular torsion (Science)",
    "Allergies (Science)",
    "Pneumonia (Science)",
    "Tuberculosis (Science)",
    "Malaria (Science)",
    "Alzheimer's (Science)",
    "Autism (Science)",
    "OCD (Science)",

    // Fictional Characters (20 words)
    "Sherlock Holmes (Entertainment)",
    "Harry Potter (Entertainment)",
    "Peter Griffin (Entertainment)",
    "Mickey Mouse (Entertainment)",
    "Superman (Entertainment)",
    "Batman (Entertainment)",
    "Spider-Man (Entertainment)",
    "Elsa from FROZEN(Entertainment)",
    "Woody (Entertainment)",
    "Buzz Lightyear (Entertainment)",
    "Shrek (Entertainment)",
    "Goku (Entertainment)",
    "Pikachu (Entertainment)",
    "Homer Simpson (Entertainment)",
    "Spongebob (Entertainment)",
    "Scooby Doo (Entertainment)",
    "Hello Kitty (Entertainment)",
    "Peppa Pig (Entertainment)",
    "Hulk (Entertainment)",
    "James Bond (Entertainment)",

    // Body Parts (20 words)
    "Brain (Science)",
    "Heart (Science)",
    "Lung (Science)",
    "Stomach (Science)",
    "Kidney (Science)",
    "Liver (Science)",
    "Eye (Science)",
    "Ear (Science)",
    "Nose (Science)",
    "Mouth (Science)",
    "Hand (Science)",
    "Foot (Science)",
    "Arm (Science)",
    "Leg (Science)",
    "Finger (Science)",
    "Toe (Science)",
    "Neck (Science)",
    "Shoulder (Science)",
    "Knee (Science)",
    "Elbow (Science)",

    // Everyday Actions (20 words)
    "Sleeping (Activity)",
    "Eating (Activity)",
    "Drinking (Activity)",
    "Walking (Activity)",
    "Running (Activity)",
    "Reading (Activity)",
    "Writing (Activity)",
    "Talking (Activity)",
    "Listening (Activity)",
    "Singing (Activity)",
    "Dancing (Activity)",
    "Cooking (Activity)",
    "Cleaning (Activity)",
    "Shopping (Activity)",
    "Driving (Activity)",
    "Working (Activity)",
    "Studying (Activity)",
    "Playing (Activity)",
    "Smiling (Activity)",
    "Laughing (Activity)",

    // Abstract Concepts (20 words)
    "Time (Concept)",
    "Space (Concept)",
    "Freedom (Concept)",
    "Justice (Concept)",
    "Truth (Concept)",
    "Beauty (Concept)",
    "Happiness (Concept)",
    "Sadness (Concept)",
    "Courage (Concept)",
    "Wisdom (Concept)",
    "Knowledge (Concept)",
    "Love (Concept)",
    "Hope (Concept)",
    "Peace (Concept)",
    "War (Concept)",
    "Chaos (Concept)",
    "Order (Concept)",
    "Dream (Concept)",
    "Memory (Concept)",
    "Future (Concept)",

    // Brands/Companies (20 words)
    "Apple (Brand)",
    "Google (Brand)",
    "Nike (Brand)",
    "Coca-Cola (Brand)",
    "Pepsi (Brand)",
    "McDonald's (Brand)",
    "Starbucks (Brand)",
    "Amazon (Brand)",
    "Microsoft (Brand)",
    "Samsung (Brand)",
    "Sony (Brand)",
    "Toyota (Brand)",
    "Mercedes-Benz (Brand)",
    "BMW (Brand)",
    "HBO (Brand)",
    "Disney (Brand)",
    "Facebook (Brand)",
    "Instagram (Brand)",
    "YouTube (Brand)",
    "Netflix (Brand)",
    "TikTok (Brand)",
    "Adidas (Brand)",
    "Nike (Brand)",
    "Puma (Brand)",
    "Louis Vuitton (Brand)",
    "Gucci (Brand)",
    "Rolex (Brand)",
    
    // Famous People (20 words) - The most popular and globally recognized
    "Michael Jackson (Person)",
    "Trump (Person)",
    "Taylor Swift (Person)",
    "Cristiano Ronaldo (Person)",
    "Lionel Messi (Person)",
    "Dwayne 'The Rock' Johnson (Person)",
    "Barack Obama (Person)",
    "The Weeknd (Person)",
    "Elon Musk (Person)",
    "Albert Einstein (Person)",
    "Isaac Newton (Person)",
    "William Shakespeare (Person)",
    "Sachin Tendulkar (Person)",
    "Steve Jobs (Person)",
    "Elvis Presley (Person)",
    "Virat Kohli (Person)", 
    "LeBron James (Person)",
    "Jeff Bezos (Person)",
    "Bill Gates (Person)",
    "Narendra Modi (Person)",
    "Mahatma Gandhi (Person)",
    "Adolf Hitler (Person)",
    "Allu Arjun (Person)",
    "Rajinikanth (Person)",
    "Kamal Haasan (Person)",
    "Ajith Kumar (Person)",
    "Vijay (Person)",
    "Dhanush (Person)",
    "Vikram (Person)",
    "Suriya (Person)",
    "Rajinikanth (Person)", 
    "Prabhas (Person)",
    "Mahesh Babu (Person)",
    "Prakash Raj (Person)",
    "Nagarjuna (Person)",
    "Chiranjeevi (Person)",
    "Rajesh Khanna (Person)",
    "Amitabh Bachchan (Person)",
    "Shah Rukh Khan (Person)",
];