const keywords = [
    // Entertainment
    "Ratatouille (Entertainment)",
    "Titanic (Entertainment)",
    "The Lion King (Entertainment)",
    "Jurassic Park (Entertainment)",
    "Star Wars (Entertainment)",
    "Harry Potter (Entertainment)",
    "Inception (Entertainment)",
    "The Matrix (Entertainment)",
    "Avatar (Entertainment)",
    "Forrest Gump (Entertainment)",
    "Pulp Fiction (Entertainment)",
    "The Godfather (Entertainment)",
    "Shawshank Redemption (Entertainment)",
    "Spirited Away (Entertainment)",
    "Parasite (Entertainment)",
    "Interstellar (Entertainment)",
    "Gladiator (Entertainment)",
    "E.T. (Entertainment)",
    "Toy Story (Entertainment)",
    "Finding Nemo (Entertainment)",
    "Sherlock Holmes (Entertainment)",
    "Peter Griffin (Entertainment)",
    "Mickey Mouse (Entertainment)",
    "Superman (Entertainment)",
    "Batman (Entertainment)",
    "Spider-Man (Entertainment)",
    "Elsa from FROZEN (Entertainment)",
    "Woody (Entertainment)",
    "Buzz Lightyear (Entertainment)",
    "Shrek (Entertainment)",
    "Goku (Entertainment)",
    "Pikachu (Entertainment)",
    "Homer Simpson (Entertainment)",
    "Spongebob (Entertainment)",
    "Scooby Doo (Entertainment)",
    "Hello Kitty (Entertainment)",
    "Peppa Pig (Entertainment)",
    "Hulk (Entertainment)",
    "James Bond (Entertainment)",

    // Brands
    "Apple (Brand)",
    "Google (Brand)",
    "Nike (Brand)",
    "Coca-Cola (Brand)",
    "Pepsi (Brand)",
    "McDonald's (Brand)",
    "Starbucks (Brand)",
    "Amazon (Brand)",
    "Microsoft (Brand)",
    "Samsung (Brand)",
    "Sony (Brand)",
    "Toyota (Brand)",
    "Mercedes-Benz (Brand)",
    "BMW (Brand)",
    "Netflix (Brand)",
    "Disney (Brand)",
    "Adidas (Brand)",
    "Facebook (Brand)",
    "Instagram (Brand)",
    "YouTube (Brand)",
  
    // Activity
    "Football (Activity)",
    "Basketball (Activity)",
    "Soccer (Activity)",
    "Tennis (Activity)",
    "Golf (Activity)",
    "Swimming (Activity)",
    "Running (Activity)",
    "Cycling (Activity)",
    "Volleyball (Activity)",
    "Baseball (Activity)",
    "Hockey (Activity)",
    "Boxing (Activity)",
    "Gymnastics (Activity)",
    "Skiing (Activity)",
    "Snowboarding (Activity)",
    "Surfing (Activity)",
    "Skateboarding (Activity)",
    "Cricket (Activity)",
    "Badminton (Activity)",
    "Rugby (Activity)",
    "Sleeping (Activity)",
    "Eating (Activity)",
    "Drinking (Activity)",
    "Walking (Activity)",
    "Reading (Activity)",
    "Writing (Activity)",
    "Talking (Activity)",
    "Listening (Activity)",
    "Singing (Activity)",
    "Dancing (Activity)",
    "Cooking (Activity)",
    "Cleaning (Activity)",
    "Shopping (Activity)",
    "Driving (Activity)",
    "Working (Activity)",
    "Studying (Activity)",
    "Playing (Activity)",
    "Smiling (Activity)",
    "Laughing (Activity)",
  
    // Concept
    "Time (Concept)",
    "Space (Concept)",
    "Freedom (Concept)",
    "Justice (Concept)",
    "Truth (Concept)",
    "Beauty (Concept)",
    "Happiness (Concept)",
    "Sadness (Concept)",
    "Courage (Concept)",
    "Wisdom (Concept)",
    "Knowledge (Concept)",
    "Love (Concept)",
    "Hope (Concept)",
    "Peace (Concept)",
    "War (Concept)",
    "Chaos (Concept)",
    "Order (Concept)",
    "Dream (Concept)",
    "Memory (Concept)",
    "Future (Concept)",
    "Gravity (Concept)",
    "Evolution (Concept)",
    "Photosynthesis (Concept)",
    "DNA (Concept)",
    "Atoms (Concept)",
    "Physics (Concept)",
    "Chemistry (Concept)",
    "Biology (Concept)",
    "Astronomy (Concept)",
    "Geology (Concept)",
    "Experiment (Concept)",
    "Hypothesis (Concept)",
    "Theory (Concept)",
    "Electricity (Concept)",
    "Magnetism (Concept)",
    "Psychology (Concept)",
  
    // Object
    "Rocket (Object)",
    "Car (Object)",
    "Bus (Object)",
    "Train (Object)",
    "Plane (Object)",
    "Boat (Object)",
    "Ship (Object)",
    "Submarine (Object)",
    "Helicopter (Object)",
    "Bicycle (Object)",
    "Motorcycle (Object)",
    "Skateboard (Object)",
    "Scooter (Object)",
    "Tractor (Object)",
    "Truck (Object)",
    "Tricycle (Object)",
    "Ambulance (Object)",
    "Fire Truck (Object)",
    "Hot Air Balloon (Object)",
    "Spaceship (Object)",
    "Computer (Object)",
    "Laptop (Object)",
    "Phone (Object)",
    "Tablet (Object)",
    "Camera (Object)",
    "Microphone (Object)",
    "Speaker (Object)",
    "Headphones (Object)",
    "Keyboard (Object)",
    "Mouse (Object)",
    "Printer (Object)",
    "Scanner (Object)",
    "Projector (Object)",
    "Battery (Object)",
    "Internet (Object)",
    "Software (Object)",
    "Robot (Object)",
    "Drone (Object)",
    "Smartwatch (Object)",
    "Virtual Reality (Object)",
    "Chair (Object)",
    "Table (Object)",
    "Sofa (Object)",
    "Bed (Object)",
    "Lamp (Object)",
    "Mirror (Object)",
    "Rug (Object)",
    "Curtain (Object)",
    "Television (Object)",
    "Refrigerator (Object)",
    "Oven (Object)",
    "Microwave (Object)",
    "Dishwasher (Object)",
    "Washing Machine (Object)",
    "Vacuum Cleaner (Object)",
    "Broom (Object)",
    "Mop (Object)",
    "Clock (Object)",
    "Vase (Object)",
    "Plate (Object)",
    "T-shirt (Object)",
    "Jeans (Object)",
    "Dress (Object)",
    "Jacket (Object)",
    "Shoes (Object)",
    "Hat (Object)",
    "Scarf (Object)",
    "Gloves (Object)",
    "Socks (Object)",
    "Boots (Object)",
    "Sandals (Object)",
    "Sweater (Object)",
    "Hoodie (Object)",
    "Pajamas (Object)",
    "Belt (Object)",
    "Wallet (Object)",
    "Chain (Object)",
    "Backpack (Object)",
    "Umbrella (Object)",
    "Glasses (Object)",
  
    // Living Thing
    "Tiger (Living Thing)",
    "Elephant (Living Thing)",
    "Dolphin (Living Thing)",
    "Kangaroo (Living Thing)",
    "Chimpanzee (Living Thing)",
    "Eagle (Living Thing)",
    "Shark (Living Thing)",
    "Penguin (Living Thing)",
    "Octopus (Living Thing)",
    "Giraffe (Living Thing)",
    "Panda (Living Thing)",
    "Wolf (Living Thing)",
    "Fox (Living Thing)",
    "Bear (Living Thing)",
    "Lion (Living Thing)",
    "Zebra (Living Thing)",
    "Crocodile (Living Thing)",
    "Snake (Living Thing)",
    "Owl (Living Thing)",
    "Butterfly (Living Thing)",
    "Doctor (Living Thing)",
    "Astronaut (Living Thing)",
    "Teacher (Living Thing)",
    "Engineer (Living Thing)",
    "Chef (Living Thing)",
    "Artist (Living Thing)",
    "Musician (Living Thing)",
    "Pilot (Living Thing)",
    "Police Officer (Living Thing)",
    "Firefighter (Living Thing)",
    "Lawyer (Living Thing)",
    "Scientist (Living Thing)",
    "Writer (Living Thing)",
    "Farmer (Living Thing)",
    "Architect (Living Thing)",
    "Photographer (Living Thing)",
    "Dancer (Living Thing)",
    "Nurse (Living Thing)",
    "Veterinarian (Living Thing)",
    "Librarian (Living Thing)",
    "Michael Jackson (Living Thing)",
    "Trump (Living Thing)",
    "Taylor Swift (Living Thing)",
    "Cristiano Ronaldo (Living Thing)",
    "Lionel Messi (Living Thing)",
    "Dwayne 'The Rock' Johnson (Living Thing)",
    "Barack Obama (Living Thing)",
    "The Weeknd (Living Thing)",
    "Elon Musk (Living Thing)",
    "Albert Einstein (Living Thing)",
    "Isaac Newton (Living Thing)",
    "William Shakespeare (Living Thing)",
    "Sachin Tendulkar (Living Thing)",
    "Steve Jobs (Living Thing)",
    "Elvis Presley (Living Thing)",
    "Virat Kohli (Living Thing)",
    "LeBron James (Living Thing)",
    "Jeff Bezos (Living Thing)",
    "Bill Gates (Living Thing)",
    "Narendra Modi (Living Thing)",
    "Mahatma Gandhi (Living Thing)",
    "Adolf Hitler (Living Thing)",
    "Brain (Living Thing)",
    "Heart (Living Thing)",
    "Lung (Living Thing)",
    "Stomach (Living Thing)",
    "Kidney (Living Thing)",
    "Liver (Living Thing)",
    "Eye (Living Thing)",
    "Ear (Living Thing)",
    "Nose (Living Thing)",
    "Mouth (Living Thing)",
    "Hand (Living Thing)",
    "Foot (Living Thing)",
    "Arm (Living Thing)",
    "Leg (Living Thing)",
    "Finger (Living Thing)",
    "Toe (Living Thing)",
    "Neck (Living Thing)",
    "Shoulder (Living Thing)",
    "Knee (Living Thing)",
    "Elbow (Living Thing)"
  ];
  