const keywords = [
    // Movies (20 words)
    "Ratatouille (Movie)",
    "Titanic (Movie)",
    "The Lion King (Movie)",
    "Jurassic Park (Movie)",
    "Star Wars (Movie)",
    "Harry Potter (Movie)",
    "Inception (Movie)",
    "The Matrix (Movie)",
    "Avatar (Movie)",
    "Forrest Gump (Movie)",
    "Pulp Fiction (Movie)",
    "The Godfather (Movie)",
    "Shawshank Redemption (Movie)",
    "Spirited Away (Movie)",
    "Parasite (Movie)",
    "Interstellar (Movie)",
    "Gladiator (Movie)",
    "E.T. (Movie)",
    "Toy Story (Movie)",
    "Finding Nemo (Movie)",

    // Science (20 words)
    "Gravity (Science)",
    "Evolution (Science)",
    "Photosynthesis (Science)",
    "DNA (Science)",
    "Atoms (Science)",
    "Physics (Science)",
    "Chemistry (Science)",
    "Biology (Science)",
    "Astronomy (Science)",
    "Geology (Science)",
    "Experiment (Science)",
    "Hypothesis (Science)",
    "Theory (Science)",
    "Microscope (Science)",
    "Telescope (Science)",
    "Vaccine (Science)",
    "Electricity (Science)",
    "Magnetism (Science)",
    "psychology (Science)",
    "photosynthesis (Science)",

    // Animals (20 words)
    "Tiger (Animal)",
    "Elephant (Animal)",
    "Dolphin (Animal)",
    "Kangaroo (Animal)",
    "Chimpanzee (Animal)",
    "Eagle (Animal)",
    "Shark (Animal)",
    "Penguin (Animal)",
    "Octopus (Animal)",
    "Giraffe (Animal)",
    "Panda (Animal)",
    "Wolf (Animal)",
    "Fox (Animal)",
    "Bear (Animal)",
    "Lion (Animal)",
    "Zebra (Animal)",
    "Crocodile (Animal)",
    "Snake (Animal)",
    "Owl (Animal)",
    "Butterfly (Animal)",

    // Food & Drink (20 words)
    "Banana (Food)",
    "Pizza (Food)",
    "Sushi (Food)",
    "Pasta (Food)",
    "Taco (Food)",
    "Burger (Food)",
    "Chocolate (Food)",
    "Ice Cream (Food)",
    "Coffee (Drink)",
    "Tea (Drink)",
    "Smoothie (Drink)",
    "Watermelon (Food)",
    "Broccoli (Food)",
    "Bread (Food)",
    "Cheese (Food)",
    "Soup (Food)",
    "Salad (Food)",
    "Juice (Drink)",
    "Soda (Drink)",
    "Milk (Drink)",

    // Professions (20 words)
    "Doctor (Profession)",
    "Astronaut (Profession)",
    "Teacher (Profession)",
    "Engineer (Profession)",
    "Chef (Profession)",
    "Artist (Profession)",
    "Musician (Profession)",
    "Pilot (Profession)",
    "Police Officer (Profession)",
    "Firefighter (Profession)",
    "Lawyer (Profession)",
    "Scientist (Profession)",
    "Writer (Profession)",
    "Farmer (Profession)",
    "Architect (Profession)",
    "Photographer (Profession)",
    "Dancer (Profession)",
    "Nurse (Profession)",
    "Veterinarian (Profession)",
    "Librarian (Profession)",

    // Places (General) (20 words)
    "Library (Place)",
    "Hospital (Place)",
    "Museum (Place)",
    "Restaurant (Place)",
    "Supermarket (Place)",
    "Airport (Place)",
    "School (Place)",
    "Park (Place)",
    "Beach (Place)",
    "Forest (Place)",
    "Mountain (Place)",
    "Desert (Place)",
    "Island (Place)",
    "City (Place)",
    "Village (Place)",
    "Bridge (Place)",
    "Castle (Place)",
    "Factory (Place)",
    "Port (Place)",
    "Zoo (Place)",

    // Nature (20 words)
    "Ocean (Nature)",
    "River (Nature)",
    "Lake (Nature)",
    "Volcano (Nature)",
    "Waterfall (Nature)",
    "Rainbow (Nature)",
    "Cloud (Nature)",
    "Sun (Nature)",
    "Moon (Nature)",
    "Star (Nature)",
    "Planet (Nature)",
    "Flower (Nature)",
    "Tree (Nature)",
    "Bush (Nature)",
    "Grass (Nature)",
    "Rock (Nature)",
    "Sand (Nature)",
    "Snow (Nature)",
    "Ice (Nature)",
    "Cave (Nature)",

    // Household Items (20 words)
    "Chair (Household Item)",
    "Table (Household Item)",
    "Sofa (Household Item)",
    "Bed (Household Item)",
    "Lamp (Household Item)",
    "Mirror (Household Item)",
    "Rug (Household Item)",
    "Curtain (Household Item)",
    "Television (Household Item)",
    "Refrigerator (Household Item)",
    "Oven (Household Item)",
    "Microwave (Household Item)",
    "Dishwasher (Household Item)",
    "Washing Machine (Household Item)",
    "Vacuum Cleaner (Household Item)",
    "Broom (Household Item)",
    "Mop (Household Item)",
    "Clock (Household Item)",
    "Vase (Household Item)",
    "Plate (Household Item)",

    // Clothing & Accessories (20 words)
    "T-shirt (Clothing & Accessories)",
    "Jeans (Clothing & Accessories)",
    "Dress (Clothing & Accessories)",
    "Jacket (Clothing & Accessories)",
    "Shoes (Clothing & Accessories)",
    "Hat (Clothing & Accessories)",
    "Scarf (Clothing & Accessories)",
    "Gloves (Clothing & Accessories)",
    "Socks (Clothing & Accessories)",
    "Boots (Clothing & Accessories)",
    "Sandals (Clothing & Accessories)",
    "Sweater (Clothing & Accessories)",
    "Hoodie (Clothing & Accessories)",
    "Pajamas (Clothing & Accessories)",
    "Belt (Clothing & Accessories)",
    "Wallet (Clothing & Accessories)",
    "chain (Clothing & Accessories)",
    "Backpack (Clothing & Accessories)",
    "Umbrella (Clothing & Accessories)",
    "Glasses (Clothing & Accessories)",

    // Vehicles (20 words)
    "Rocket (Vehicle)",
    "Car (Vehicle)",
    "Bus (Vehicle)",
    "Train (Vehicle)",
    "Plane (Vehicle)",
    "Boat (Vehicle)",
    "Ship (Vehicle)",
    "Submarine (Vehicle)",
    "Helicopter (Vehicle)",
    "Bicycle (Vehicle)",
    "Motorcycle (Vehicle)",
    "Skateboard (Vehicle)",
    "Scooter (Vehicle)",
    "Tractor (Vehicle)",
    "Truck (Vehicle)",
    "Tricycle (Vehicle)",
    "Ambulance (Vehicle)",
    "Fire Truck (Vehicle)",
    "Hot Air Balloon (Vehicle)",
    "Spaceship (Vehicle)",

    // Technology (20 words)
    "Computer (Technology)",
    "Laptop (Technology)",
    "Phone (Technology)",
    "Tablet (Technology)",
    "Camera (Technology)",
    "Microphone (Technology)",
    "Speaker (Technology)",
    "Headphones (Technology)",
    "Keyboard (Technology)",
    "Mouse (Technology)",
    "Printer (Technology)",
    "Scanner (Technology)",
    "Projector (Technology)",
    "Battery (Technology)",
    "Internet (Technology)",
    "Software (Technology)",
    "Robot (Technology)",
    "Drone (Technology)",
    "Smartwatch (Technology)",
    "Virtual Reality (Technology)",

    // Sports (20 words)
    "Football (Sport)",
    "Basketball (Sport)",
    "Soccer (Sport)",
    "Tennis (Sport)",
    "Golf (Sport)",
    "Swimming (Sport)",
    "Running (Sport)",
    "Cycling (Sport)",
    "Volleyball (Sport)",
    "Baseball (Sport)",
    "Hockey (Sport)",
    "Boxing (Sport)",
    "Gymnastics (Sport)",
    "Skiing (Sport)",
    "Snowboarding (Sport)",
    "Surfing (Sport)",
    "Skateboarding (Sport)",
    "Cricket (Sport)",
    "Badminton (Sport)",
    "Rugby (Sport)",

    // Health Conditions (20 words) - Includes Diseases, Disorders, Fractures
    "Down Syndrome (Health Condition)",
    "Flu (Health Condition)",
    "Diabetes (Health Condition)",
    "Heart Attack (Health Condition)",
    "Cancer (Health Condition)",
    "Asthma (Health Condition)",
    "Anxiety (Health Condition)", 
    "Depression (Health Condition)", 
    "Concussion (Health Condition)", 
    "Fracture (Health Condition)", 
    "multiple personality disorder (Health Condition)",
    "Migraine (Health Condition)",
    "testicular torsion (Health Condition)",
    "Allergies (Health Condition)",
    "Pneumonia (Health Condition)",
    "Tuberculosis (Health Condition)",
    "Malaria (Health Condition)",
    "Alzheimer's (Health Condition)",
    "Autism (Health Condition)",
    "OCD (Health Condition)",

    // Fictional Characters (20 words)
    "Sherlock Holmes (Character)",
    "Harry Potter (Character)",
    "Peter Griffin (Character)",
    "Mickey Mouse (Character)",
    "Superman (Character)",
    "Batman (Character)",
    "Spider-Man (Character)",
    "Elsa from FROZEN(Character)",
    "Woody (Character)",
    "Buzz Lightyear (Character)",
    "Shrek (Character)",
    "Goku (Character)",
    "Pikachu (Character)",
    "Homer Simpson (Character)",
    "Spongebob (Character)",
    "Scooby Doo (Character)",
    "Hello Kitty (Character)",
    "Peppa Pig (Character)",
    "Hulk (Character)",
    "James Bond (Character)",

    // Body Parts (20 words)
    "Brain (Body Part)",
    "Heart (Body Part)",
    "Lung (Body Part)",
    "Stomach (Body Part)",
    "Kidney (Body Part)",
    "Liver (Body Part)",
    "Eye (Body Part)",
    "Ear (Body Part)",
    "Nose (Body Part)",
    "Mouth (Body Part)",
    "Hand (Body Part)",
    "Foot (Body Part)",
    "Arm (Body Part)",
    "Leg (Body Part)",
    "Finger (Body Part)",
    "Toe (Body Part)",
    "Neck (Body Part)",
    "Shoulder (Body Part)",
    "Knee (Body Part)",
    "Elbow (Body Part)",

    // Everyday Actions (20 words)
    "Sleeping (Action)",
    "Eating (Action)",
    "Drinking (Action)",
    "Walking (Action)",
    "Running (Action)",
    "Reading (Action)",
    "Writing (Action)",
    "Talking (Action)",
    "Listening (Action)",
    "Singing (Action)",
    "Dancing (Action)",
    "Cooking (Action)",
    "Cleaning (Action)",
    "Shopping (Action)",
    "Driving (Action)",
    "Working (Action)",
    "Studying (Action)",
    "Playing (Action)",
    "Smiling (Action)",
    "Laughing (Action)",

    // Abstract Concepts (20 words)
    "Time (Concept)",
    "Space (Concept)",
    "Freedom (Concept)",
    "Justice (Concept)",
    "Truth (Concept)",
    "Beauty (Concept)",
    "Happiness (Concept)",
    "Sadness (Concept)",
    "Courage (Concept)",
    "Wisdom (Concept)",
    "Knowledge (Concept)",
    "Love (Concept)",
    "Hope (Concept)",
    "Peace (Concept)",
    "War (Concept)",
    "Chaos (Concept)",
    "Order (Concept)",
    "Dream (Concept)",
    "Memory (Concept)",
    "Future (Concept)",

    // Brands/Companies (20 words)
    "Apple (Brand)",
    "Google (Brand)",
    "Nike (Brand)",
    "Coca-Cola (Brand)",
    "Pepsi (Brand)",
    "McDonald's (Brand)",
    "Starbucks (Brand)",
    "Amazon (Brand)",
    "Microsoft (Brand)",
    "Samsung (Brand)",
    "Sony (Brand)",
    "Toyota (Brand)",
    "Mercedes-Benz (Brand)",
    "BMW (Brand)",
    "Netflix (Brand)",
    "Disney (Brand)",
    "Adidas (Brand)",
    "Facebook (Brand)",
    "Instagram (Brand)",
    "YouTube (Brand)",

    // Famous People (20 words) - The most popular and globally recognized
    "Michael Jackson (Person)",
    "Trump (Person)",
    "Taylor Swift (Person)",
    "Cristiano Ronaldo (Person)",
    "Lionel Messi (Person)",
    "Dwayne 'The Rock' Johnson (Person)",
    "Barack Obama (Person)",
    "The Weeknd (Person)",
    "Elon Musk (Person)",
    "Albert Einstein (Person)",
    "Isaac Newton (Person)",
    "William Shakespeare (Person)",
    "Sachin Tendulkar (Person)",
    "Steve Jobs (Person)",
    "Elvis Presley (Person)",
    "Virat Kohli (Person)", 
    "LeBron James (Person)",
    "Jeff Bezos (Person)",
    "Bill Gates (Person)",
    "Narendra Modi (Person)",
    "Mahatma Gandhi (Person)",
    "Adolf Hitler (Person)"
];